<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Welcome extends CI_Controller {

	public function __construct()
	{
		parent::__construct();
		$this->load->library('instamojo');
		$this->load->helper('url');
		$api = new Instamojo\Instamojo('54085f4df81272b423e21fcca3ffcad9', 'cca50cabc21965e9951590039e491110', 'https://test.instamojo.com/api/1.1/');
	}

	public function index()
	{
		$this->load->view('welcome_message');
	}

	public function makePayment()
	{
		$this->load->view('payment_view');
	}

	public function processPayment()
	{
		//print_r($this->input->post()); die;

		try {
			    $response = $api->paymentRequestCreate(array(
			        "purpose" => "FIFA 16",
			        "amount" => "3499",
			        "send_email" => true,
			        "email" => "foo@example.com",
			        "redirect_url" => "http://www.example.com/handle_redirect.php"
			        ));
			    print_r($response);
			}
			catch (Exception $e) {
			    print('Error: ' . $e->getMessage());
			}
	}

	public function get_all()
	{
		$result = $this->instamojo->all_payment_request();

		print_r($result);
	}


	public function pay_request()
	{
		
		$pay = $this->instamojo->pay_request( 

						$amount = "200" , 
						$purpose = "TEST" , 
						$buyer_name = "rbbqq" , 
						$email = "rajeevbbqq@gmail.com" , 
						$phone = "89xxxx2017" ,
		     			$send_email = 'TRUE' , 
		     			$send_sms = 'TRUE' , 
		     			$repeated = 'FALSE'

		     		);


		$payment_id = $pay['id'];  // <= Payment Id
							      // print_r($pay) ; <=  Prints all the data from the request

	}


	public function status()
	{
		$paymentId  = '84c04c212ccb4a8ba8c87e35ec4a2511'  ; // $paymentId generated by Instamojo
		$status     = $this->instamojo->status($paymentId);

		print_r($status);
	}


	public function payment_status()
	{
		$requestId = '84c04c212ccb4a8ba8c87e35ec4a2511'  ;
		$status    = $this->instamojo->status($requestId);

		print_r($status) ;
	}


	public function show()
	{
		$data['request_id'] = '84c04c212ccb4a8ba8c87e35ec4a2511' ;
		$this->load->view('instamojo' ,$data);
	}
}
